-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.family_space (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  household_type text NOT NULL DEFAULT 'couple_kids'::text CHECK (household_type = ANY (ARRAY['couple_kids'::text, 'single_parent'::text, 'extended'::text, 'blended'::text, 'partners'::text, 'solo'::text, 'other'::text])),
  month_start_day integer NOT NULL DEFAULT 1 CHECK (month_start_day >= 1 AND month_start_day <= 28),
  base_currency text NOT NULL DEFAULT 'USD'::text CHECK (base_currency = ANY (ARRAY['USD'::text, 'EUR'::text, 'GBP'::text, 'ZAR'::text, 'CAD'::text, 'AUD'::text, 'KES'::text, 'NGN'::text, 'INR'::text, 'ZWG'::text])),
  rate_profile text NOT NULL DEFAULT 'rbz'::text CHECK (rate_profile = ANY (ARRAY['rbz'::text, 'market'::text])),
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT family_space_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profile (
  id uuid NOT NULL,
  phone text UNIQUE,
  name text NOT NULL,
  avatar text NOT NULL DEFAULT '🙂'::text,
  language text NOT NULL DEFAULT 'en'::text CHECK (language = ANY (ARRAY['en'::text, 'es'::text, 'fr'::text, 'pt'::text, 'sn'::text, 'nd'::text])),
  ui_size text NOT NULL DEFAULT 'normal'::text CHECK (ui_size = ANY (ARRAY['normal'::text, 'large'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  email text UNIQUE,
  avatar_url text,
  CONSTRAINT user_profile_pkey PRIMARY KEY (id),
  CONSTRAINT user_profile_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.membership (
  space_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['owner'::text, 'co_parent'::text, 'adult'::text, 'contributor'::text, 'teen'::text, 'kid'::text, 'viewer'::text])),
  sharing_level text NOT NULL DEFAULT 'shared_only'::text CHECK (sharing_level = ANY (ARRAY['full'::text, 'shared_only'::text])),
  private_pocket_enabled boolean NOT NULL DEFAULT false,
  invite_status text NOT NULL DEFAULT 'invited'::text CHECK (invite_status = ANY (ARRAY['invited'::text, 'active'::text, 'left'::text])),
  invite_code text,
  joined_at timestamp with time zone,
  CONSTRAINT membership_pkey PRIMARY KEY (space_id, user_id),
  CONSTRAINT membership_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT membership_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profile(id)
);
CREATE TABLE public.account (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  name text NOT NULL,
  kind text NOT NULL DEFAULT 'cash'::text CHECK (kind = ANY (ARRAY['cash'::text, 'ecocash'::text, 'bank_card'::text, 'bank_transfer'::text, 'zipit'::text, 'innbucks'::text, 'other'::text])),
  owner_member_id uuid,
  currency text NOT NULL CHECK (currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  sharing text NOT NULL DEFAULT 'shared'::text CHECK (sharing = ANY (ARRAY['shared'::text, 'private'::text])),
  opening_balance_minor bigint NOT NULL DEFAULT 0 CHECK (opening_balance_minor >= 0),
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT account_owner_member_id_fkey FOREIGN KEY (owner_member_id) REFERENCES public.user_profile(id)
);
CREATE TABLE public.category (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  name text NOT NULL,
  icon text NOT NULL DEFAULT '🧾'::text,
  kind text NOT NULL DEFAULT 'expense'::text CHECK (kind = ANY (ARRAY['expense'::text, 'income'::text])),
  is_personal boolean NOT NULL DEFAULT false,
  CONSTRAINT category_pkey PRIMARY KEY (id),
  CONSTRAINT category_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id)
);
CREATE TABLE public.transaction (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  account_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['expense'::text, 'income'::text, 'transfer'::text])),
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL CHECK (currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  category_id uuid,
  member_id uuid NOT NULL,
  method text NOT NULL DEFAULT 'cash'::text CHECK (method = ANY (ARRAY['cash'::text, 'ecocash'::text, 'mobile_money'::text, 'bank_card'::text, 'bank_transfer'::text, 'zipit'::text, 'innbucks'::text, 'agent'::text, 'other'::text])),
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  note text NOT NULL DEFAULT ''::text,
  voice_note_uri text,
  receipt_uri text,
  recurring_rule_id uuid,
  split_group_id uuid,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  updated_by uuid,
  CONSTRAINT transaction_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT transaction_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id),
  CONSTRAINT transaction_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category(id),
  CONSTRAINT transaction_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.user_profile(id),
  CONSTRAINT transaction_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profile(id),
  CONSTRAINT transaction_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.envelope (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  name text NOT NULL,
  icon text NOT NULL DEFAULT '🧾'::text,
  limit_minor bigint NOT NULL CHECK (limit_minor >= 0),
  limit_currency text NOT NULL CHECK (limit_currency = ANY (ARRAY['USD'::text, 'EUR'::text, 'GBP'::text, 'ZAR'::text, 'CAD'::text, 'AUD'::text, 'KES'::text, 'NGN'::text, 'INR'::text, 'ZWG'::text])),
  period text NOT NULL DEFAULT 'monthly'::text CHECK (period = ANY (ARRAY['monthly'::text, 'term'::text, 'custom'::text])),
  rollover text NOT NULL DEFAULT 'reset'::text CHECK (rollover = ANY (ARRAY['reset'::text, 'rollover'::text, 'accumulate'::text])),
  sharing text NOT NULL DEFAULT 'shared'::text CHECK (sharing = ANY (ARRAY['shared'::text, 'personal'::text])),
  linked_goal_id uuid,
  sort_order integer NOT NULL DEFAULT 0,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  template_key text,
  created_by uuid,
  archived_at timestamp with time zone,
  archived_by uuid,
  CONSTRAINT envelope_pkey PRIMARY KEY (id),
  CONSTRAINT envelope_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT envelope_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profile(id),
  CONSTRAINT envelope_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.envelope_tx (
  envelope_id uuid NOT NULL,
  transaction_id uuid NOT NULL,
  allocated_minor bigint NOT NULL CHECK (allocated_minor > 0),
  currency text NOT NULL CHECK (currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  CONSTRAINT envelope_tx_pkey PRIMARY KEY (envelope_id, transaction_id),
  CONSTRAINT envelope_tx_envelope_id_fkey FOREIGN KEY (envelope_id) REFERENCES public.envelope(id),
  CONSTRAINT envelope_tx_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transaction(id)
);
CREATE TABLE public.goal (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  name text NOT NULL,
  icon text NOT NULL DEFAULT '🎯'::text,
  target_minor bigint NOT NULL CHECK (target_minor > 0),
  target_currency text NOT NULL CHECK (target_currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  deadline date,
  owner_member_id uuid,
  auto_save_rule jsonb,
  is_kid_jar boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'done'::text, 'archived'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  archived_at timestamp with time zone,
  archived_by uuid,
  CONSTRAINT goal_pkey PRIMARY KEY (id),
  CONSTRAINT goal_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT goal_owner_member_id_fkey FOREIGN KEY (owner_member_id) REFERENCES public.user_profile(id),
  CONSTRAINT goal_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profile(id),
  CONSTRAINT goal_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.goal_tx (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  goal_id uuid NOT NULL,
  member_id uuid NOT NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL CHECK (currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  note text NOT NULL DEFAULT ''::text,
  at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT goal_tx_pkey PRIMARY KEY (id),
  CONSTRAINT goal_tx_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goal(id),
  CONSTRAINT goal_tx_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.user_profile(id),
  CONSTRAINT goal_tx_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.mukando (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  name text NOT NULL,
  contribution_minor bigint NOT NULL CHECK (contribution_minor > 0),
  currency text NOT NULL CHECK (currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  frequency text NOT NULL DEFAULT 'monthly'::text CHECK (frequency = ANY (ARRAY['weekly'::text, 'fortnightly'::text, 'monthly'::text])),
  total_rounds integer NOT NULL CHECK (total_rounds > 0),
  current_round integer NOT NULL DEFAULT 1 CHECK (current_round >= 1),
  started_on date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'done'::text, 'archived'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  round_order ARRAY NOT NULL DEFAULT '{}'::text[],
  CONSTRAINT mukando_pkey PRIMARY KEY (id),
  CONSTRAINT mukando_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id)
);
CREATE TABLE public.mukando_member (
  mukando_id uuid NOT NULL,
  user_id uuid NOT NULL,
  round_order integer NOT NULL CHECK (round_order >= 1),
  collected_minor bigint NOT NULL DEFAULT 0,
  collected_on timestamp with time zone,
  CONSTRAINT mukando_member_pkey PRIMARY KEY (mukando_id, user_id),
  CONSTRAINT mukando_member_mukando_id_fkey FOREIGN KEY (mukando_id) REFERENCES public.mukando(id),
  CONSTRAINT mukando_member_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profile(id)
);
CREATE TABLE public.mukando_event (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mukando_id uuid NOT NULL,
  round_no integer NOT NULL CHECK (round_no >= 1),
  kind text NOT NULL CHECK (kind = ANY (ARRAY['paid'::text, 'collected'::text])),
  member_id uuid NOT NULL,
  proof_uri text,
  at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mukando_event_pkey PRIMARY KEY (id),
  CONSTRAINT mukando_event_mukando_id_fkey FOREIGN KEY (mukando_id) REFERENCES public.mukando(id),
  CONSTRAINT mukando_event_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.user_profile(id)
);
CREATE TABLE public.shopping_list (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  name text NOT NULL,
  linked_envelope_id uuid,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'done'::text])),
  template_of uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT shopping_list_pkey PRIMARY KEY (id),
  CONSTRAINT shopping_list_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT shopping_list_linked_envelope_id_fkey FOREIGN KEY (linked_envelope_id) REFERENCES public.envelope(id),
  CONSTRAINT shopping_list_template_of_fkey FOREIGN KEY (template_of) REFERENCES public.shopping_list(id)
);
CREATE TABLE public.list_item (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  list_id uuid NOT NULL,
  name text NOT NULL,
  qty integer NOT NULL DEFAULT 1 CHECK (qty > 0),
  est_price_minor bigint NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text CHECK (currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  added_by uuid NOT NULL,
  assigned_to uuid,
  state text NOT NULL DEFAULT 'tobuy'::text CHECK (state = ANY (ARRAY['tobuy'::text, 'incart'::text, 'done'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  checked_out boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  actual_price_minor bigint CHECK (actual_price_minor IS NULL OR actual_price_minor >= 0),
  actual_currency text,
  purchased_by uuid,
  CONSTRAINT list_item_pkey PRIMARY KEY (id),
  CONSTRAINT list_item_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.shopping_list(id),
  CONSTRAINT list_item_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.user_profile(id),
  CONSTRAINT list_item_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profile(id),
  CONSTRAINT list_item_purchased_by_fkey FOREIGN KEY (purchased_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.chore (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  name text NOT NULL,
  star_value integer NOT NULL DEFAULT 1 CHECK (star_value >= 1 AND star_value <= 10),
  assignee_member_id uuid,
  recurrence text NOT NULL DEFAULT 'daily'::text CHECK (recurrence = ANY (ARRAY['once'::text, 'daily'::text, 'weekly'::text, 'custom'::text])),
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  state text NOT NULL DEFAULT 'todo'::text CHECK (state = ANY (ARRAY['todo'::text, 'waiting'::text, 'confirmed'::text])),
  is_archived boolean NOT NULL DEFAULT false,
  archived_at timestamp with time zone,
  archived_by uuid,
  CONSTRAINT chore_pkey PRIMARY KEY (id),
  CONSTRAINT chore_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT chore_assignee_member_id_fkey FOREIGN KEY (assignee_member_id) REFERENCES public.user_profile(id),
  CONSTRAINT chore_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.chore_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chore_id uuid NOT NULL,
  done_on date NOT NULL DEFAULT CURRENT_DATE,
  state text NOT NULL CHECK (state = ANY (ARRAY['claimed'::text, 'confirmed'::text])),
  claimed_by uuid NOT NULL,
  confirmed_by uuid,
  CONSTRAINT chore_log_pkey PRIMARY KEY (id),
  CONSTRAINT chore_log_chore_id_fkey FOREIGN KEY (chore_id) REFERENCES public.chore(id),
  CONSTRAINT chore_log_claimed_by_fkey FOREIGN KEY (claimed_by) REFERENCES public.user_profile(id),
  CONSTRAINT chore_log_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.kid_request (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  requester_id uuid NOT NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL CHECK (currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  reason text NOT NULL DEFAULT ''::text,
  kind text NOT NULL DEFAULT 'money'::text CHECK (kind = ANY (ARRAY['money'::text, 'expense_proposal'::text])),
  envelope_id uuid,
  state text NOT NULL DEFAULT 'pending'::text CHECK (state = ANY (ARRAY['pending'::text, 'approved'::text, 'declined'::text])),
  decided_by uuid,
  decision_note text,
  decided_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT kid_request_pkey PRIMARY KEY (id),
  CONSTRAINT kid_request_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT kid_request_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.user_profile(id),
  CONSTRAINT kid_request_envelope_id_fkey FOREIGN KEY (envelope_id) REFERENCES public.envelope(id),
  CONSTRAINT kid_request_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.earning (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  member_id uuid NOT NULL,
  note text NOT NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL CHECK (currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT earning_pkey PRIMARY KEY (id),
  CONSTRAINT earning_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT earning_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.user_profile(id)
);
CREATE TABLE public.rate_snapshot (
  day date NOT NULL,
  source text NOT NULL CHECK (source = ANY (ARRAY['rbz'::text, 'market'::text])),
  usd_zwg numeric NOT NULL CHECK (usd_zwg > 0::numeric),
  captured_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rate_snapshot_pkey PRIMARY KEY (day, source)
);
CREATE TABLE public.activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  actor_id uuid NOT NULL,
  action text NOT NULL,
  entity text NOT NULL,
  entity_id uuid,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  at timestamp with time zone NOT NULL DEFAULT now(),
  prev_hash text,
  hash text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT activity_log_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT activity_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.user_profile(id)
);
CREATE TABLE public.recurring_rule (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  name text NOT NULL,
  emoji text NOT NULL DEFAULT ''::text,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL DEFAULT 'USD'::text CHECK (currency = ANY (ARRAY['USD'::text, 'ZWG'::text])),
  envelope_id uuid,
  member_id uuid,
  method text NOT NULL DEFAULT 'cash'::text CHECK (method = ANY (ARRAY['cash'::text, 'ecocash'::text, 'mobile_money'::text, 'bank_card'::text, 'bank_transfer'::text, 'zipit'::text, 'innbucks'::text, 'agent'::text, 'other'::text])),
  frequency text NOT NULL DEFAULT 'monthly'::text CHECK (frequency = ANY (ARRAY['weekly'::text, 'monthly'::text, 'term'::text])),
  next_due date NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  archived_at timestamp with time zone,
  archived_by uuid,
  CONSTRAINT recurring_rule_pkey PRIMARY KEY (id),
  CONSTRAINT recurring_rule_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT recurring_rule_envelope_id_fkey FOREIGN KEY (envelope_id) REFERENCES public.envelope(id),
  CONSTRAINT recurring_rule_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.user_profile(id),
  CONSTRAINT recurring_rule_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profile(id),
  CONSTRAINT recurring_rule_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.family_invite (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL,
  code text NOT NULL UNIQUE,
  role text NOT NULL CHECK (role = ANY (ARRAY['adult'::text, 'co_parent'::text, 'teen'::text, 'kid'::text, 'viewer'::text])),
  email text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  revoked_at timestamp with time zone,
  accepted_by uuid,
  accepted_at timestamp with time zone,
  CONSTRAINT family_invite_pkey PRIMARY KEY (id),
  CONSTRAINT family_invite_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT family_invite_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profile(id),
  CONSTRAINT family_invite_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.push_device (
  token text NOT NULL,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  platform text NOT NULL CHECK (platform = ANY (ARRAY['android'::text, 'ios'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT push_device_pkey PRIMARY KEY (token),
  CONSTRAINT push_device_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.budget_cycle_plan (
  id uuid NOT NULL,
  space_id uuid NOT NULL,
  cycle_start date NOT NULL,
  income_mode text NOT NULL CHECK (income_mode = ANY (ARRAY['known_monthly'::text, 'as_earned'::text])),
  expected_income_minor bigint,
  currency text NOT NULL DEFAULT 'USD'::text,
  allocations jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'closed'::text])),
  copied_from date,
  closed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT budget_cycle_plan_pkey PRIMARY KEY (id),
  CONSTRAINT budget_cycle_plan_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT budget_cycle_plan_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.family_chat_message (
  id uuid NOT NULL,
  space_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  text text NOT NULL,
  status text NOT NULL DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['sent'::text, 'delivered'::text, 'read'::text])),
  reference_type text CHECK (reference_type = ANY (ARRAY['task'::text, 'shopping_list'::text, 'expense'::text, 'goal'::text, 'contribution'::text])),
  reference_id text,
  reference_title text,
  reference_meta text,
  is_system boolean NOT NULL DEFAULT false,
  sender_name text,
  sender_avatar text,
  deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  media_url text,
  media_type text,
  sticker text,
  CONSTRAINT family_chat_message_pkey PRIMARY KEY (id),
  CONSTRAINT family_chat_message_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT family_chat_message_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.user_profile(id)
);
CREATE TABLE public.family_debt (
  id uuid NOT NULL,
  space_id uuid NOT NULL,
  name text NOT NULL,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['iOwe'::text, 'owedToMe'::text, 'familyLoan'::text])),
  principal_minor bigint NOT NULL CHECK (principal_minor > 0),
  currency text NOT NULL,
  counterparty_member_id uuid,
  due_date timestamp with time zone,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'settled'::text, 'archived'::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT family_debt_pkey PRIMARY KEY (id),
  CONSTRAINT family_debt_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT family_debt_counterparty_member_id_fkey FOREIGN KEY (counterparty_member_id) REFERENCES public.user_profile(id),
  CONSTRAINT family_debt_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.debt_repayment (
  id uuid NOT NULL,
  debt_id uuid NOT NULL,
  member_id uuid NOT NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL,
  paid_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT debt_repayment_pkey PRIMARY KEY (id),
  CONSTRAINT debt_repayment_debt_id_fkey FOREIGN KEY (debt_id) REFERENCES public.family_debt(id),
  CONSTRAINT debt_repayment_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.user_profile(id)
);
CREATE TABLE public.contribution_campaign (
  id uuid NOT NULL,
  space_id uuid NOT NULL,
  name text NOT NULL,
  target_minor bigint NOT NULL CHECK (target_minor > 0),
  currency text NOT NULL,
  deadline timestamp with time zone NOT NULL,
  created_by uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'closed'::text, 'archived'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contribution_campaign_pkey PRIMARY KEY (id),
  CONSTRAINT contribution_campaign_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT contribution_campaign_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profile(id)
);
CREATE TABLE public.contribution_pledge (
  id uuid NOT NULL,
  campaign_id uuid NOT NULL,
  member_id uuid NOT NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contribution_pledge_pkey PRIMARY KEY (id),
  CONSTRAINT contribution_pledge_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.contribution_campaign(id),
  CONSTRAINT contribution_pledge_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.user_profile(id)
);
CREATE TABLE public.contribution_payment (
  id uuid NOT NULL,
  campaign_id uuid NOT NULL,
  member_id uuid NOT NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL,
  paid_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contribution_payment_pkey PRIMARY KEY (id),
  CONSTRAINT contribution_payment_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.user_profile(id),
  CONSTRAINT contribution_payment_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.contribution_campaign(id)
);
CREATE TABLE public.transaction_split (
  id uuid NOT NULL,
  space_id uuid NOT NULL,
  transaction_id uuid NOT NULL,
  envelope_id uuid NOT NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT transaction_split_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_split_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.family_space(id),
  CONSTRAINT transaction_split_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transaction(id),
  CONSTRAINT transaction_split_envelope_id_fkey FOREIGN KEY (envelope_id) REFERENCES public.envelope(id)
);